apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-fix-operator
  labels:
    app: probe-fix-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: probe-fix-operator
  template:
    metadata:
      labels:
        app: probe-fix-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 8 }}
{{- end }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "/healthz.sh"
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
